### ISSUE TITLE
merge upstream?

### ISSUE THREAD

**Issue by divansantana** [tws-inc/gitea-group-sync#1]
Is there a PR to merge this upstearm.

https://github.com/go-gitea/gitea/issues/1395

Would be great.

**Comment by alexattws** [comment]
This is a stand-alone project. It is not meant to be part of Gitea code base. It uses Gitea API to make changes in Gitea.

If the model turns out to work for most people, maybe someone can integrate some of this code into Gitea.

**Comment by tboerger** [comment]
I'm sure that there would be a bigger interest in getting a groups sync into the Gitea core, there is the long standing issue at https://github.com/go-gitea/gitea/issues/1395

**Comment by alexattws** [comment]
There are different ways of achieving group sync. What we are doing with gitea-group-sync is matching LDAP group names to Gitea team names in all organizations. If there is an exact match, then we add users to the team that are in the matched LDAP group. Maybe that works for some people, but not others. For example, maybe you want to manually map LDAP groups to Gitea teams via a web UI or have some other automatic mapping policy.

**Comment by divansantana** [comment]
Cool. Either way I'll give it a try - thanks.

**Comment by alexattws** [comment]
No problem. It would be nice to get some feedback if you get around to it. Thanks.
