### ISSUE TITLE
group sync not working with private organizations

### ISSUE THREAD

**Issue by gremlintomsk** [tws-inc/gitea-group-sync#17]
Hi, group sync not working with private gitea organizations, only with public orgs. Is there is any way to import LDAP groups into gitea private org?

**Comment by selukov** [comment]
It does not matter whether the organization is private or public, the user will be added/deleted if the user is  added/deleted with the corresponding Teams-group on your LDAP server and the user must be included in the group of users who have access to your gitea server. The Team group name on gitea server and on the LDAP server must be the same.

**Comment by gremlintomsk** [comment]
gitea 1.15.0

i have admin user and some private orgs(not owner of them). i create gitea token and configure groupsync script. it works only with public orgs. i try to use gitea api(api/swagger) and check which orgs i can view(admin/orgs). but it shows same public orgs as a groupsync script.
groupsync with public orgs works perfectly

**Comment by selukov** [comment]
Do you use the gitea admin token? Try creating and adding a new comma-separated key. GITEA_TOKEN=c00c810bb668c63ce7cd8057411d2f560eac469c,2c02df6959d012dee8f5da3539f63223417c4bbe

**Comment by gremlintomsk** [comment]
Yes, i do. Recreating new admin token does not work.

**Comment by selukov** [comment]
I checked on the test server, adding users to a private organization is successful

[![2021-09-13-03-48-46.png](https://i.postimg.cc/Jn59ZW9L/2021-09-13-03-48-46.png)](https://postimg.cc/Vr5GP2fG)

[![2021-09-13-03-34-50.png](https://i.postimg.cc/DftqLbP7/2021-09-13-03-34-50.png)](https://postimg.cc/bd9Djr55)

**Comment by gremlintomsk** [comment]
did you use gitea 1.15.0?

**Comment by selukov** [comment]
Change the version to 1.15.1 or 1.15.2. The Gitea API version 1.15.0 does not return private organizations. I do not know why, it seems there was a bug

[![2021-09-13-11-51-58.png](https://i.postimg.cc/rFg0d7h2/2021-09-13-11-51-58.png)](https://postimg.cc/BXLQk79m)

Gitea API 1.15.0
[![2021-09-13-12-10-01.png](https://i.postimg.cc/CLtZHbVc/2021-09-13-12-10-01.png)](https://postimg.cc/zVCXqbvh)
Gitea API 1.15.2
[![2021-09-13-12-15-34.png](https://i.postimg.cc/63g3LNky/2021-09-13-12-15-34.png)](https://postimg.cc/Hc0ddFsg)

**Comment by gremlintomsk** [comment]
upgrade gitea to 1.15.2 fix problem. thanks
