### ISSUE TITLE
Gitea 1.16.7 can't add users to teams

### ISSUE THREAD

**Issue by gremlintomsk** [tws-inc/gitea-group-sync#18]
Hi. After upgrade gitea from 1.15.2 to 1.16.7. App did't add users to teams in gitea. 

**May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 Begin an organization review: OrganizationName= liferay, OrganizationId= 18
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 6 teams were found in liferay organization
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 Skip synchronization in the Owners team
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 The LDAP ldap.server.local has 18 users corresponding to team project_incomand_developer
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 The gitea http://localhost:3000 has 15 users corresponding to team project_incomand_developer Teamid=10
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 can be added users list [{0  sberezina} {0  nbelokrylova} {0  aborovets}]
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 must be del users list []
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 The LDAP ldap.server.local has 7 users corresponding to team project_incomand_manager
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 The gitea http://localhost:3000 has 5 users corresponding to team project_incomand_manager Teamid=11
May 08 06:54:02 gitea.incomand.local run.sh[18152]: 2022/05/08 06:54:02 can be added users list [{0  aborovets} {0  gjagarian}]**

May be they change API?

**Comment by localleon** [comment]
Hey, 

There should be an offical feature in the lateste Gitea Release that supports syncing ldap and groups. 

So this project probaly isnt needed anymore....

**Comment by toshywoshy** [comment]
I do not think so, the Gitea LDAP group sync is expected in the 1.17 release
However I think that will not be the same functionality as this project.
I like the simplicity of your design and the way it works, it fits my use cases exactly.
As for this issue, please check my PR #19 , it seems to solve the problem on newer gitea releases.

**Comment by gremlintomsk** [comment]
PR#19 works for me, thx

**Comment by maxguru** [comment]
Looks like @toshywoshy's commit fixed this issue. If anybody is still having issues, please let us know.
