### ISSUE TITLE
Config Files and binary 

### ISSUE THREAD

**Issue by localleon** [tws-inc/gitea-group-sync#6]
Greetings,

i would propose to introduce an Config-File in YAML Format instead of Enviroment Variables. The config File could be specified via a  "--config" flag. 

This would help with readability of the current config and you could track changes in your configuration easier. Is this something you guys are interested? Then i could work on a PR.

Kind Regards,

**Comment by alexattws** [comment]
Sounds like a great idea. However, we should probably continue to support the environment variables option for backwards compatibility, etc.

**Comment by alexattws** [comment]
Thanks for the pull request!
