### ISSUE TITLE
No License attached to this project

### ISSUE THREAD

**Issue by lbedford** [tws-inc/gitea-group-sync#8]
This project does exactly what I need, but there's no license on the code, so I believe
that means I cannot use it.

https://choosealicense.com/no-permission/

It would be great if you could add one,
Thanks.

**Comment by alexattws** [comment]
Looks like we forgot to add a license.

Gitea is licensed under the MIT License. I think we should also use this license. What do people think?

@ykorzikowski, @thoscut, @localleon, @Ingomancer, you guys have contributions in this repository. Do you agree to license this code under the MIT license retroactively?

**Comment by selukov** [comment]
I confirm

**Comment by ingomancer** [comment]
I agree

**Comment by thoscut** [comment]
I agree

**Comment by ykorzikowski** [comment]
I agree

**Comment by localleon** [comment]
I agree
